#!/usr/bin/env bash
# Build wrapper — the Evaluator and Generator both call this so "how to build" lives in one place.
# Generated by the agent-harness skill. Edit the command below to match your stack.
set -euo pipefail
cd "$(dirname "$0")/.."
{{BUILD_CMD}}
echo "build ok"
