#!/usr/bin/env bash
# Test wrapper — single source of truth for "how to run the tests".
# Generated by the agent-harness skill. Edit the command below to match your stack.
set -euo pipefail
cd "$(dirname "$0")/.."
{{TEST_CMD}}
